### PR TITLE
Node data dump 1.5

### PR DESCRIPTION
**Pull request by LauraStelzner-TRI**
Adding function needed for other node_data_dump branches

### CODE REVIEW

**Comment by athackst** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3#-:-KjEaSGGpUBxMPcocIS5:bnfp4nl)*

**Comment by tinawright** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/task_behavior_engine/tree.py, line 399 at r1](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3#-KjEbCNXHGml6n2ahaND:-KjEbCNYro7IVT-fb2wA:b-sn4jhr) ([raw file](https://github.com/toyotaresearchinstitute/task_behavior_engine/blob/2b558c80bfc8009715988c63f7a3edfe565ab8d9/src/task_behavior_engine/tree.py#L399)):*
> ```Python
>         """
>         return self._blackboard.get_memory(self._id)
>     
> ```

FYI: excess whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3#-:-KjEbFuhx5ki1kHaAQtW:bnfp4nl)*

**Comment by tinawright** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3)*

**Comment by LauraStelzner-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/task_behavior_engine/tree.py, line 399 at r1](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3#-KjEbCNXHGml6n2ahaND:-KjEeTk1Vx5n3cY150vv:b-896fix) ([raw file](https://github.com/toyotaresearchinstitute/task_behavior_engine/blob/2b558c80bfc8009715988c63f7a3edfe565ab8d9/src/task_behavior_engine/tree.py#L399)):*
<details><summary><i>Previously, tinawright (Tina Wright (TRI)) wrote…</i></summary><blockquote>

FYI: excess whitespace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3)*

**Comment by tinawright** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toyotaresearchinstitute/task_behavior_engine/3)*

**Pull request merged**
